# SPDX-FileCopyrightText: 2026 paintress-team
# SPDX-License-Identifier: GPL-3.0-or-later

"""Paintress head profiles: generated Python bindings.

DO NOT EDIT. Generated by paintress_protocol_gen from profiles/*.yaml.
frame fingerprint 0x108865B9; heads: c4n180, c6n90
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Dict, Optional, Tuple


# --- The frame: what the firmware guarantees -------------------------

# CRC-32 of the canonical frame string, reported by IDENTIFY. It covers
# the line size, clocks, edges and packing (everything the firmware
# constrains) and nothing about which head is fitted, which the board
# cannot know. Every head below shares it, so one firmware build serves
# them all.
FRAME_FINGERPRINT = 0x108865B9

# Line sizes: a data line travels over the wire packed to BYTES_PER_LINE
# bytes and is stored expanded to PSRAM_LINE_SIZE bytes on the device.
BYTES_PER_LINE = 147
USB_LINE_SIZE = 147  # alias of BYTES_PER_LINE
PSRAM_LINE_SIZE = 196

# Frame shape: one bus block spans EDGE_COUNT bits over CLOCK_COUNT
# clocks of BITS_PER_CLOCK bits (one per data pin, on both edges).
EDGE_COUNT = 392
CLOCK_COUNT = 196
BITS_PER_CLOCK = 6
FRAME_DATA_PINS = 3
PACKING = "contiguous"


# --- The heads: what a job was packed for ----------------------------

@dataclass(frozen=True)
class HeadProfile:
    """One printhead's scalars.

    ``head_fingerprint`` identifies the head a job was packed for. It is
    checked host-side, between the job and the machine's configuration,
    never against the firmware: which head is bolted on is not
    something the board can report.
    """

    name: str
    head_fingerprint: int
    nozzle_count: int
    channels: Tuple[str, ...]
    # Reference plumbing: the ink feeding each of the head's outputs, in
    # the order you read the head facing it. Per-setup overrides go to
    # the encoder's --ink-map, not here.
    slot_inks: Tuple[str, ...]
    data_buses: int
    window_enable_map: str
    column_gap_mm: float
    group_gap_mm: Optional[float]
    base_dpi: int

    @property
    def channel_count(self) -> int:
        return len(self.channels)

    @property
    def idle_data_buses(self) -> int:
        """Frame pins this head leaves unwired: shifted out, connected
        to nothing. Non-zero is how a head rides a wider frame."""
        return FRAME_DATA_PINS - self.data_buses


HEADS: Dict[str, HeadProfile] = {
    "c4n180": HeadProfile(
        name="c4n180",
        head_fingerprint=0x93255450,
        nozzle_count=60,
        channels=("C", "M", "Y", "K"),
        slot_inks=("K", "C", "M", "Y"),
        data_buses=2,
        window_enable_map="00000000000000000000000000000010",
        column_gap_mm=6.0,
        group_gap_mm=None,
        base_dpi=720,
    ),
    "c6n90": HeadProfile(
        name="c6n90",
        head_fingerprint=0x9C244CD5,
        nozzle_count=90,
        channels=("C", "M", "Y", "K", "LC", "LM"),
        slot_inks=("K", "Y", "LM", "LC", "C", "M"),
        data_buses=3,
        window_enable_map="00000000000000100000000000000000",
        column_gap_mm=0.842,
        group_gap_mm=7.051,
        base_dpi=360,
    ),
}


DEFAULT_HEAD = "c6n90"


def head(name: str) -> HeadProfile:
    """The profile for ``name``, or a ValueError naming the known heads."""
    try:
        return HEADS[name]
    except KeyError:
        raise ValueError(
            f"unknown head {name!r} (known: {', '.join(sorted(HEADS))})"
        ) from None
